/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;

public interface CKCameraManagerInterface<T extends View> {
  void setFlashMode(T view, @Nullable String value);
  void setFocusMode(T view, @Nullable String value);
  void setZoomMode(T view, @Nullable String value);
  void setZoom(T view, double value);
  void setMaxZoom(T view, double value);
  void setTorchMode(T view, @Nullable String value);
  void setCameraType(T view, @Nullable String value);
  void setScanBarcode(T view, boolean value);
  void setShowFrame(T view, boolean value);
  void setLaserColor(T view, @Nullable Integer value);
  void setFrameColor(T view, @Nullable Integer value);
  void setRatioOverlay(T view, @Nullable String value);
  void setRatioOverlayColor(T view, @Nullable Integer value);
  void setResetFocusTimeout(T view, int value);
  void setResetFocusWhenMotionDetected(T view, boolean value);
  void setResizeMode(T view, @Nullable String value);
  void setScanThrottleDelay(T view, int value);
  void setShutterPhotoSound(T view, boolean value);
  void setShutterAnimationDuration(T view, int value);
  void setOutputPath(T view, @Nullable String value);
}
